### ISSUE TITLE
Add Orange Attacks

### ISSUE THREAD

**Issue by BloomChara** [Jcw87/c2-sans-fight#23] opened 2017-05-25 16:17 UTC
I was thinking that maybe you can add orange attacks for custom attacks. I know it doesn't have to be a priority for you, since Sans doesn't use orange attacks, but I think it can open a lot for customs. You do whatever you want with this project, it's good enough as is and that's all I need.

**Comment by iKNIFEu** [comment] 2020-01-10 10:36
agreed

**Comment by iKNIFEu** [comment] 2020-02-14 15:42
Kinda easy to add Jcw.

**Comment by Jcw87** [comment] 2020-02-15 04:25
It's not a matter of ease, it's a matter of finding the time and motivation to do it. And when I do find that time and motivation, It's usually motivation to add one specific thing. The last time I was motivated to work on this project, it was an attempt to replace the janky CSV accidental programming language with an actual scripting language. I would have more progress on that, but javascript is notoriously hard to sandbox, and one of the better approaches I've seen is no longer supported by the author, which means extra work for me.

**Comment by iKNIFEu** [comment] 2020-04-10 15:53
> It's not a matter of ease, it's a matter of finding the time and motivation to do it. And when I do find that time and motivation, It's usually motivation to add one specific thing. The last time I was motivated to work on this project, it was an attempt to replace the janky CSV accidental programming language with an actual scripting language. I would have more progress on that, but javascript is notoriously hard to sandbox, and one of the better approaches I've seen is no longer supported by the author, which means extra work for me.

hey, sorry for being toxic in the past few months, I want to tell you how to add "Orange Attacks" in construct. As you can see in the image below, this will make the attack orange, where do you put it? under the blue attack.
![image](https://user-images.githubusercontent.com/58735494/79003728-742f9980-7b53-11ea-9158-c2b7421dc792.png)

Now for how it works:
See that? It's under color 1, which is blue, I wanted to add Orange attacks, so I did this:
Copy and paste the color 1 under it.
Make it color 2, and instead of making it "custommovement is moving", it will be "CustomMovement Overall = 0", that'll make it hit you when you are not moving.
![image](https://user-images.githubusercontent.com/58735494/79003884-d8525d80-7b53-11ea-9ca5-e18e23ae4bf9.png)

And then, you are done! It's very easy and fun to do, also, I don't want you to do it *right now*. I want you to do it when you have the motivation and time to do it. Thank you for all your hard work jcw87.

**Comment by Jcw87** [comment] 2020-04-15 10:32
I didn't need you to explain this. I actually already worked out the logic of how I would implement orange bones back when I wrote the logic for the blue bones, as it is literally just a duplicate of the blue bone logic with some conditions inverted. Yes, that does mean I toyed with the idea of adding orange bones before this issue was opened, which is why the variable is an integer named Color and not a boolean named Blue. As I said before, it's about the time and motivation to actually go in, add the code, do the requisite testing, etc.

But, if you want to make a pull request for this, I'll consider accepting it. Make sure that you attach a testing attack (not as part of the commit, just to the github PR)

**Comment by iKNIFEu** [comment] 2020-04-15 16:14
Okay.. I won't do that, I just thought you didn't know how to do that. Sorry for wasting your time.

**Comment by Jcw87** [comment] 2021-05-29 20:41
I added an orange bone. It can be used by setting the color value to 2. I picked the orange color from the orange lasers. Fun fact: The decompiled Undertale code shows that the color of the lasers is set by a variable named "blue", and can have values of 1 (for blue) and 2 (for orange)
```
	if(self.blue == 1) draw_set_color(Red=14 ,Green=192 ,Blue=253);
	if(self.blue == 2) draw_set_color(Red=255 ,Green=160 ,Blue=64);
```

**Closed by Jcw87** 2021-05-29 20:41 UTC
Labels: enhancement
