### ISSUE TITLE
[Feature Request] "Automatic Jumps"

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#61] opened 2020-01-27 18:36 UTC
Well, I want automatic jumps so badly, I can't do ANYTHING without it.

**Comment by Jcw87** [comment] 2020-01-28 03:38
Duplicate of #5

Do not open new issues about the same topic, and especially do not open a new issue to reply to a comment on an existing issue. You can still comment on #59. Closed doesn't mean you can't continue leaving comments. That's what locked is for.

**Closed by Jcw87** 2020-01-28 03:38 UTC
