### ISSUE TITLE
add the ability for left click to be used instead of space bar

### ISSUE THREAD

**Issue by amhooman** [Jcw87/c2-sans-fight#147] opened 2023-03-17 20:03 UTC
I am trying to make this work on the wii u browser. It works there, but I cant start the game, as the wii u doesn't have a space bar

**Comment by Jcw87** [comment] 2023-03-17 20:11
Duplicate of #143
You already made an issue for this, and I already explained why it isn't worth trying to make this work in the Wii U browser.

**Closed** 2023-03-17 20:27 UTC
Labels: duplicate, wontfix
