### ISSUE TITLE
Bone Stab cheese not working

### ISSUE THREAD

**Issue by marcociav** [Jcw87/c2-sans-fight#153] opened 2023-06-21 20:30 UTC
In the game, if you long press all 4 arrow buttons during any bonestab sequence, you will automatically dodge all attacks in the sequence (cheese).

However, this is not the case in bad time simulator.

Is there any way to implement this in-game cheese?

**Comment by Jcw87** [comment] 2023-06-22 00:56
I specifically intended to prevent that cheese. This is a duplicate of #5, #31, #59, #61, and #62. That's 5 existing issues for this.

**Closed by Jcw87** 2023-06-22 00:56 UTC
