### ISSUE TITLE
Automatic Jump for blue soul.

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#62] opened 2020-02-14 15:48 UTC
I really try hard in construct 2 to add auto jump, but it's all in vain, is it possible for you to add Autojump? I could add orange bones, orange souls, green souls, green bones, red bones, but text and autojump, is it possible for you to add autojump.
if you do have discord, jcw, please contact me:
iKNIFEu#8660.
I promise if you do that, I'll help you in your c2-sans-fight to be more undertale-like:
some bones look different, not all are the same
Gasterblasters blast1 is a bit away from blast2 and blast3
And Etc for the people's custom attacks.

**Comment by Jcw87** [comment] 2020-02-15 04:03
Duplicate of #5

I strongly doubt that you would be able to contribute anything meaningful, as I explained to you in #59 exactly how you could change the code to get the result you want, and you still haven't managed to do it yourself. Not only that, you haven't given me any reason to believe that you actually did try doing it yourself, and are not just lying in an attempt to get what you want. Furthermore, you have demonstrated an inability to follow the simple directions I gave you in #61. Do NOT create duplicate issues. This is your last warning. If you do it again, you will be blocked from this repository.

As I've already explained in #5, not being able to auto-jump is an intentional change. If you really want this bad enough, you can do it yourself using the info I gave you in #59

**Closed by Jcw87** 2020-02-15 04:03 UTC

**Comment by iKNIFEu** [comment] 2020-02-16 14:59
Wait wait, sorry! the closed ones are not visibled, I'm really sorry, I shouldn't have made you angry, I'm really sorry, I won't do that again.

**Comment by Jcw87** [comment] 2020-02-17 00:08
GitHub automatically subscribes you to issues that you create, and will send you e-mails for every single reply to it. You can reply to any of these e-mails to leave another comment on an issue. These e-mails also contain a link to the issue that was replied to, allowing you to reply to it there. There's also the notification bell icon at the top right corner of the site that will list those replies, including links. In addition, while browsing issues, you can change the filter to show closed issues, or delete the filter completely and see everything. There were many avenues for you to have seen my replies and make new replies without creating a new issue.

So, the question I have to ask myself, is how could you miss all of these options? If you really did miss all of these options, that creates even more doubt for your ability to assist with the game, and further indicates that you probably lied previously. If you didn't, then you lied to me just now. I strongly dislike liars.

You have given me many reasons to distrust you, but **I am still willing to point you in the right direction, so long as you make an honest effort.** You can start by answering the questions I asked you in #59. If you cannot, then **stop wasting my time.**
